V2 examples
kadena-io/marmalade pull request #183
Opened 2024-01-16 12:00 UTC by wooglie

This PR adds three example policies, tests, and documentation explaining each

# Fixed Issuance Policy

Fixed Issuance Policy is an example module of Marmalade which provides a simple method to program a fractional token. Because there are various ways to program fractional tokens, the contract only provides the simplest feature that is required for fractional tokens, and encourages users to extend upon the
contract. 

# Onchain Manifest Policy

The `onchain-manifest-policy-v1` module is a part of Marmalade that provides onchain manifest storage for `marmalade-v2`. It implements the `kip.token-policy-v2` interface and enables the management of token manifests on the blockchain.

# Timed Mint Policy

The Timed Mint Policy is a module of Marmalade that enables the minting of tokens within a specific time window. This policy restricts the minting of tokens to a predefined period and provides control over the minting process.

# Soul Bound Policy
is still in progress and you can check the status here #177

2024-01-17 09:48 UTC, ggobugi27 requested changes

2024-01-17 09:48 UTC, ggobugi27 commented on examples/policies/fixed-issuance-policy/fixed-issuance-policy-v1.pact
> +  (defconst ADMIN-KS:string "marmalade-v2.marmalade-contract-admin")
We can add 
`marmalade-examples.marmalade-examples-admin` keyset in marmalade.repl (L76~) like the v2 and sale namespaces, and then update ADMIN-KS

2024-01-17 09:48 UTC, ggobugi27 commented on examples/policies/timed-mint-policy/timed-mint-policy-v1.pact
> +    mint-start-time:time
We're using timestamps in general, so it'd be nice to take in times as integers, in timestamps. Users can use `to-timestamp` function if they'd like to pass in time in time format.

2024-01-17 09:48 UTC, ggobugi27 commented on examples/policies/timed-mint-policy/timed-mint-policy-v1.pact
> +      (enforce (>= (at 'block-time (chain-data))  mint-start-time) "Mint has not started yet")
We can replace `(at 'block-time (chain-data))` to `(curr-time)` function in `util-v1`, which returns the block time in timestamps.

2024-01-24 15:31 UTC, wooglie commented on .github/workflows/test-concrete-policies.yml
You're right, and I think some new general name would be better than splitting the code

2024-01-25 08:18 UTC, jermaine150 approved these changes

2024-01-25 08:26 UTC, ggobugi27 approved these changes

2024-01-25 11:20 UTC, merged