Private token policy
kadena-io/marmalade pull request #195
Opened 2024-04-09 10:35 UTC by wooglie

# Private token policy

Private token policy allows creators to make an airdrop without revealing the metadata of the token beforehand. The token URI can be revealed at any time, making the metadata known to all.

## Requirements:

Concrete policy `guard-policy` must be used in conjunction with `private-token-policy` to make sure only an authorized account can update the token URI.

While creating a token, the URI should be the hash of the actual URI. This can be calculated using a local call to the node so there is no trace recorded on the chain.

## Specification, tables, capabilities, events:

**Schemas**: `revealed-tokens-schema` is a schema that stores which tokens have been revealed
  - `revealed`: shows if the URI has been revealed.

**Tables**: `revealed-tokens` table stores which tokens have been revealed.
  - `id`: the id of the token

**Capabilities**:
 - `GOVERNANCE`: enforces access control of contract upgrades.

**Events**:
 - `TOKEN_REVEALED (token-id uri)`: Emitted when the token URI has been revealed.

## Policy Functions

**`enforce-init`:** Enforced during `marmalade-v2.ledger.create-token`, and will ensure the concrete `guard-policy` is present along with the URI guard.

**`enforce-mint`:** Enabled without limitation.

**`enforce-burn`:** Enabled without limitation.

**`enforce-offer`:** Enabled without limitation.

**`enforce-buy`:** Enabled without limitation.

**`enforce-withdraw`:** Enabled without limitation.

**`enforce-transfer`:** Enabled without limitation.

**`enforce-update-uri`:** Enabled without limitation.

**`reveal-uri`:** Will make sure that the saved hash of the URI matches the hashed new URI and will invoke `marmalade-v2.ledger.update-uri`.

**`is-revealed`:** Check if the URI has been revealed.

2024-04-09 13:41 UTC, jermaine150 approved these changes

2024-04-11 11:45 UTC, wooglie commented
The failing test should be resolved with this PR #197

2024-05-16 10:50 UTC, ggobugi27 requested changes

2024-05-16 10:50 UTC, ggobugi27 commented on examples/policies/private-token-policy/private-token-policy-v1.pact
> +    (> (length (filter (lambda (policy) (= policy marmalade-v2.guard-policy-v1)) policies)) 0))
You should stringify the `marmalade-v2.guard-policy-v1` because the modref comparison depends on its version (hash).

2024-05-16 10:50 UTC, ggobugi27 commented on examples/policies/private-token-policy/private-token-policy-v1.pact
> +    (> (length (filter (lambda (policy) (= policy marmalade-v2.guard-policy-v1)) policies)) 0))
We have a function specifically built to check this for concrete-policies: 
https://github.com/kadena-io/marmalade/blob/main/pact/marmalade-util/util-v1.pact#L79:L86

2024-05-16 10:57 UTC, ggobugi27 approved these changes

2024-05-16 10:58 UTC, merged