V2 ci test
kadena-io/marmalade pull request #82
Opened 2023-06-07 09:45 UTC by jermaine150

2023-06-08 14:40 UTC, ggobugi27 requested changes
Instead of adding test flows per policies, can we `(load ..-policy.repl)` into `marmalade.repl` so we have one file that tests all the policies? This would be easier for additional tests like `marmalade-util`, or other regular policies

2023-06-08 14:44 UTC, jermaine150 commented
> Instead of adding test flows per policies, can we `(load ..-policy.repl)` into `marmalade.repl` so we have one file that tests all the policies? This would make it easier to add additional tests like `marmalade-util`, or other regular policies

I added them separately on purpose so you get isolated feedback on what's failing. I don't think it's wise to bunch it all up in a single repl. 
Since we don't add a concrete-policy lightly this list won't grow indefinitely so I'm not worried about the size.

2023-06-09 01:42 UTC, ggobugi27 approved these changes

2023-06-09 06:43 UTC, nillo approved these changes

2023-06-09 10:15 UTC, merged